name: pharmacy_and_drug_store
display_name: Pharmacy & Drug Store
version: 3.1.1
theme_key: 5d469512e9cfeaa99deb334ebf6895d3
author:
  name: "Anvanto Team"
  email: "anvantoco@gmail.com"
  url: "https://anvanto.com"

meta:
  compatibility:
    from: 1.7.0.0
    to: ~

  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column

dependencies:
  modules:
    - anproductextratabs
    - anscrolltop
    - anthemeblocks
    - an_megamenu
    - an_productattributes
    - an_logo
    - an_wishlist
    - an_brandslider
    - an_hurry_up
    - an_stickyaddtocart
    - an_theme
    - an_cookie_popup
    - an_theme_dashboard

assets:
  # If you're using this theme as child and you want to load
  # the parent theme assets, uncomment this line.
  #  use_parent_assets: true

  # The following lines are showing how to load assets in your page
  # Uncomment and change value to start loading css or js files
  #  css:
  #    all:
  #      - id: custom-lib-style
  #        path: assets/css/custom-lib.css
  #    product:
  #      - id: product-style
  #        path: assets/css/product.css
  #        media: all
  #        priority: 200
  #  js:
  #    cart:
  #      - id: cat-extra-lib
  #        path: assets/js/cart-lib.js
  css:
    all:
      - id: photoswipe-css
        path: assets/css/photoswipe.css
      - id: default-skin-css
        path: assets/css/default-skin.css
  js:
    all:
      - id: cookie-js
        path: assets/js/jquery.cookie.min.js
      - id: photoswipe-js
        path: assets/js/photoswipe.min.js
      - id: photoswipe-ui-default-js
        path: assets/js/photoswipe-ui-default.min.js

global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
    to_enable:
      - ps_linklist
      - ps_featuredproducts
      - anproductextratabs
      - anscrolltop
      - anthemeblocks
      - an_megamenu
      - an_productattributes
      - an_logo
      - an_wishlist
      - an_brandslider
      - an_stickyaddtocart
      - an_theme
      - an_cookie_popup
      - an_theme_dashboard
    to_disable:
      - ps_imageslider
  hooks:
    modules_to_hook:
      displayNav1:
        - ps_contactinfo
        - anthemeblocks
      displayNav2:
        - anthemeblocks
        - ps_customersignin
        # Se quita la opcion de wishlist ya que no sera utilizada en el nav
        # - an_wishlist
      displayTopLeft:
        - an_logo
        # Se quita la opcion de shoppingcart para poder manejarlo de manera individual
        # - ps_shoppingcart
      displayTop:
        - an_megamenu
        - anthemeblocks
        - ps_searchbar
      displayTopRight:
        # Se crea un nuevo hook para manejar de manera individual el shoppingcart
        - ps_shoppingcart
      displayHome:
        - ps_featuredproducts
        - anthemeblocks
      displayFooterTop:
        - ps_socialfollow
      displayFooterBefore:
        - anthemeblocks
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
        - anthemeblocks
        - anscrolltop
      displayAdminProductsExtra:
        - ~
        - anproductextratabs
      displayProductExtraContent:
        - anproductextratabs
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
        - anthemeblocks
      displaySearch:
        - ps_searchbar
        - anthemeblocks
      displayMobileMenu:
        - an_megamenu
      displayProductListReviews:
        - an_wishlist
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - an_hurry_up
        - anthemeblocks
      displayProductAdditionalInfo2:
        - an_wishlist
        - anthemeblocks
      displayReassurance:
        - anthemeblocks
      displayOrderConfirmation2:
        - ps_featuredproducts
        - anthemeblocks
      displayCrossSellingShoppingCart:
        - ps_featuredproducts
        - anthemeblocks
      displayBeforeBodyClosingTag:
        - ~
        - anthemeblocks
      displayCartExtraProductActions:
        - ~
        - anthemeblocks
      displayCopyrightContainer:
        - ~
        - anthemeblocks
      displayCustomerAccount:
        - ~
        - anthemeblocks
        - an_wishlist
      displayProductListWishlist:
        - an_wishlist
      displayCustomerLoginFormAfter:
        - ~
        - anthemeblocks
      displayFooterProduct:
        - ~
        - an_stickyaddtocart
        - anthemeblocks
      displayHomeAfter:
        - ~
        - anthemeblocks
        - ps_emailsubscription
        - an_brandslider
      displayHomeBefore:
        - ~
        - anthemeblocks
      displayLeftColumnProduct:
        - ~
        - anthemeblocks
      displayMyAccountBlock:
        - ~
        - anthemeblocks
      displayNav:
        - ~
        - anthemeblocks
      displayNavFullWidth:
        - ~
        - anthemeblocks
      displayOrderConfirmation:
        - ~
        - anthemeblocks
      displayPaymentByBinaries:
        - ~
        - anthemeblocks
      displayPaymentTop:
        - ~
        - anthemeblocks
      displayRightColumn:
        - ~
        - anthemeblocks
      displayRightColumnProduct:
        - ~
        - anthemeblocks
      displayShoppingCart:
        - ~
        - anthemeblocks
      displayShoppingCartFooter:
        - ~
        - anthemeblocks
        - an_wishlist
      displaySliderContainerWidth:
        - ~
        - anthemeblocks
      displayTopColumn:
        - ~
        - anthemeblocks
      displayBackOfficeHeader:
        - ~
        - anthemeblocks
        - anscrolltop
        - anproductextratabs
        - an_stickyaddtocart
        - an_theme_dashboard
      displayWrapperTop:
        - anthemeblocks
      displayWrapperBottom:
        - anthemeblocks
      displayHomeSliderFullWidth:
        - anthemeblocks
      displayFooterANLiveEditor:
        - ~

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 253
      height: 253
      scope: [products]
    catalog_small:
      width: 184
      height: 184
      scope: [products]
    catalog_medium:
      width: 253
      height: 253
      scope: [products]
    catalog_large:
      width: 398
      height: 398
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
    menu_default:
      width: 98
      height: 130
      scope: [products, categories, manufacturers, suppliers]
    slider_photo:
      width: 97
      height: 97
      scope: [products, categories, manufacturers, suppliers]
    anblog_default:
      width: 690
      height: 350
      scope: []
    anblog_thumb:
      width: 690
      height: 350
      scope: []
    anblog_listing_leading_img:
      width: 690
      height: 300
      scope: []
    anblog_listing_secondary_img:
      width: 390
      height: 220
      scope: []

theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
    best-sales: layout-left-column
    new-products: layout-left-column
    prices-drop: layout-left-column
    contact: layout-left-column
